# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  e2e-test:
    docker:
      - image: node:18

    steps:
      - add_ssh_keys:
            fingerprints:
              - "a6:55:3a:79:17:47:11:87:32:0b:c2:5b:ba:d1:6c:73"
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-8 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: playwright install
          command: |
            npx playwright install --with-deps
      - run:
          name: e2e test update
          command: |
            pnpm test:e2e -u
      - run:
          name: add snapshots
          command: |
              git config user.email "image-snapshots@example.com"
              git config user.name "CircleCI Job"
              git add tests/
              git commit -am "Automatic commit from CircleCI [skip ci]"
              git push origin HEAD
      - store_artifacts:
          path: /root/project/playwright-report

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  workflow:
    jobs:
      - e2e-test
